### ISSUE TITLE
max() arg is an empty sequence

### ISSUE THREAD

**Issue by Etisti** [DevashishPrasad/CascadeTabNet#43]
Hi, I encountered this problem on testing the model epoch_13
![pbepoch13borje3](https://user-images.githubusercontent.com/42436475/83622955-fc994c00-a590-11ea-8706-6ef541010109.PNG)
on this image
![borjje_2001_3_HD](https://user-images.githubusercontent.com/42436475/83623176-45510500-a591-11ea-8230-1710c5ad25a1.png)

**Comment by AyanGadpal** [comment]
Hey @Etisti ,
I am assuming that by epoch 13 you mean "Table Bank Both table detection".
You are getting this error because the model had predicted nothing. (found 0 tables)
As for your test image with epoch 13. and 85% threshold, this is the result.
![result](https://user-images.githubusercontent.com/36962224/84379047-d152d480-ac02-11ea-8b12-6571c62b5889.PNG)
Another thing I want to point out is "Table Bank Both table detection" is only trained for table detection and will only output 1 class
```
show_result_pyplot(img, result,('Table'), score_thr=0.85)
```
Hope this resolves your issue, :)

**Comment by PurveshChhajed** [comment]
> Hey @Etisti ,
> I am assuming that by epoch 13 you mean "Table Bank Both table detection".
> You are getting this error because the model had predicted nothing. (found 0 tables)
> As for your test image with epoch 13. and 85% threshold, this is the result.
> ![result](https://user-images.githubusercontent.com/36962224/84379047-d152d480-ac02-11ea-8b12-6571c62b5889.PNG)
> Another thing I want to point out is "Table Bank Both table detection" is only trained for table detection and will only output 1 class
> 
> ```
> show_result_pyplot(img, result,('Table'), score_thr=0.85)
> ```
> 
> Hope this resolves your issue, :)





using  **show_result_pyplot(img, result,('Table'), score_thr=0.85)**  for epoch_13

giving me this.

/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:2506: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-45-c61c4fd352d4> in <module>()
     11   print("*****************************************************************")
     12   result = inference_detector(model, img)
---> 13   show_result_pyplot(img, result,('Table'), score_thr=0.85)

1 frames
/content/mmdetection/mmdet/apis/inference.py in show_result_pyplot(img, result, class_names, score_thr, fig_size)
    203     """
    204     img = show_result(
--> 205         img, result, class_names, score_thr=score_thr, show=False)
    206     plt.figure(figsize=fig_size)
    207     plt.imshow(mmcv.bgr2rgb(img))

/content/mmdetection/mmdet/apis/inference.py in show_result(img, result, class_names, score_thr, wait_time, show, out_file)
    141             visualized image is returned, otherwise None is returned.
    142     """
--> 143     assert isinstance(class_names, (tuple, list))
    144     img = mmcv.imread(img)
    145     img = img.copy()

AssertionError: 

I only want to detect tables
Thanks,
