### ISSUE TITLE
temp_lines_ver is None in borderFunc.py

### ISSUE THREAD

**Issue by mroyce1** [DevashishPrasad/CascadeTabNet#9]
Hi,

first of all, thank you for the great work. 

I tried to run main.py in ``Table Structure Recognition`` and encountered the problem that ``temp_lines_ver`` is set to None in when calling ``extract_table`` [without the lines parameter](https://github.com/DevashishPrasad/CascadeTabNet/blob/156a907fd4f891473592924b1716f8ca91c16b79/Table%20Structure%20Recognition/Functions/borderFunc.py#L20) in ``borderFunc.py``.

See [here](https://github.com/DevashishPrasad/CascadeTabNet/blob/156a907fd4f891473592924b1716f8ca91c16b79/Table%20Structure%20Recognition/Functions/borderFunc.py#L26) 

So when iterating over it [here](https://github.com/DevashishPrasad/CascadeTabNet/blob/156a907fd4f891473592924b1716f8ca91c16b79/Table%20Structure%20Recognition/Functions/borderFunc.py#L35), this will obviously throw an exception.

I'm not familiar enough with the code yet. But should be an easy one to fix for someone who is. 

Cheers

**Comment by kshitijkapadni** [comment]
Hi Marian,

The issue is because no Lines have been detected by the line detection algorithm. I would suggest you uncomment the last lines of visualization in [linedetection.py](https://github.com/DevashishPrasad/CascadeTabNet/blob/master/Table%20Structure%20Recognition/Functions/line_detection.py) file to see if the lines are detected. 

I have also added the validation in the latest commit to check if the lines are detected.
